//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceShop.ServiceCorreo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceCorreo.WebService_CorreoSoap")]
    public interface WebService_CorreoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendReserva", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendReservaResponse SendReserva(WebServiceShop.ServiceCorreo.SendReservaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendReserva", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendReservaResponse> SendReservaAsync(WebServiceShop.ServiceCorreo.SendReservaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPago", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendPagoResponse SendPago(WebServiceShop.ServiceCorreo.SendPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPago", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPagoResponse> SendPagoAsync(WebServiceShop.ServiceCorreo.SendPagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUsuarioNuevo", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse SendUsuarioNuevo(WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendUsuarioNuevo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse> SendUsuarioNuevoAsync(WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCambioContraseña", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse SendCambioContraseña(WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCambioContraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse> SendCambioContraseñaAsync(WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNewCambioContraseña", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse SendNewCambioContraseña(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendNewCambioContraseña", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse> SendNewCambioContraseñaAsync(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendActualizacionUsuario", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse SendActualizacionUsuario(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendActualizacionUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse> SendActualizacionUsuarioAsync(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPedidoDespacho", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse SendPedidoDespacho(WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPedidoDespacho", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse> SendPedidoDespachoAsync(WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEntregado", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendEntregadoResponse SendEntregado(WebServiceShop.ServiceCorreo.SendEntregadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEntregado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEntregadoResponse> SendEntregadoAsync(WebServiceShop.ServiceCorreo.SendEntregadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEnvio", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendEnvioResponse SendEnvio(WebServiceShop.ServiceCorreo.SendEnvioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendEnvio", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEnvioResponse> SendEnvioAsync(WebServiceShop.ServiceCorreo.SendEnvioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento email del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCancelado", ReplyAction="*")]
        WebServiceShop.ServiceCorreo.SendCanceladoResponse SendCancelado(WebServiceShop.ServiceCorreo.SendCanceladoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCancelado", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCanceladoResponse> SendCanceladoAsync(WebServiceShop.ServiceCorreo.SendCanceladoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendReservaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendReserva", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendReservaRequestBody Body;
        
        public SendReservaRequest() {
        }
        
        public SendReservaRequest(WebServiceShop.ServiceCorreo.SendReservaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendReservaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_pedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public SendReservaRequestBody() {
        }
        
        public SendReservaRequestBody(string rut, int id_pedido, string email) {
            this.rut = rut;
            this.id_pedido = id_pedido;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendReservaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendReservaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendReservaResponseBody Body;
        
        public SendReservaResponse() {
        }
        
        public SendReservaResponse(WebServiceShop.ServiceCorreo.SendReservaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendReservaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendReservaResult;
        
        public SendReservaResponseBody() {
        }
        
        public SendReservaResponseBody(bool SendReservaResult) {
            this.SendReservaResult = SendReservaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPago", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendPagoRequestBody Body;
        
        public SendPagoRequest() {
        }
        
        public SendPagoRequest(WebServiceShop.ServiceCorreo.SendPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_pedido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public SendPagoRequestBody() {
        }
        
        public SendPagoRequestBody(string rut, int id_pedido, string email) {
            this.rut = rut;
            this.id_pedido = id_pedido;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPagoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendPagoResponseBody Body;
        
        public SendPagoResponse() {
        }
        
        public SendPagoResponse(WebServiceShop.ServiceCorreo.SendPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendPagoResult;
        
        public SendPagoResponseBody() {
        }
        
        public SendPagoResponseBody(bool SendPagoResult) {
            this.SendPagoResult = SendPagoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUsuarioNuevoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUsuarioNuevo", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequestBody Body;
        
        public SendUsuarioNuevoRequest() {
        }
        
        public SendUsuarioNuevoRequest(WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendUsuarioNuevoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendUsuarioNuevoRequestBody() {
        }
        
        public SendUsuarioNuevoRequestBody(string rut, string email) {
            this.rut = rut;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendUsuarioNuevoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendUsuarioNuevoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponseBody Body;
        
        public SendUsuarioNuevoResponse() {
        }
        
        public SendUsuarioNuevoResponse(WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendUsuarioNuevoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendUsuarioNuevoResult;
        
        public SendUsuarioNuevoResponseBody() {
        }
        
        public SendUsuarioNuevoResponseBody(bool SendUsuarioNuevoResult) {
            this.SendUsuarioNuevoResult = SendUsuarioNuevoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCambioContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCambioContraseña", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendCambioContraseñaRequestBody Body;
        
        public SendCambioContraseñaRequest() {
        }
        
        public SendCambioContraseñaRequest(WebServiceShop.ServiceCorreo.SendCambioContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCambioContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendCambioContraseñaRequestBody() {
        }
        
        public SendCambioContraseñaRequestBody(string rut, string email) {
            this.rut = rut;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCambioContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCambioContraseñaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendCambioContraseñaResponseBody Body;
        
        public SendCambioContraseñaResponse() {
        }
        
        public SendCambioContraseñaResponse(WebServiceShop.ServiceCorreo.SendCambioContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCambioContraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendCambioContraseñaResult;
        
        public SendCambioContraseñaResponseBody() {
        }
        
        public SendCambioContraseñaResponseBody(bool SendCambioContraseñaResult) {
            this.SendCambioContraseñaResult = SendCambioContraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNewCambioContraseñaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNewCambioContraseña", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequestBody Body;
        
        public SendNewCambioContraseñaRequest() {
        }
        
        public SendNewCambioContraseñaRequest(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNewCambioContraseñaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string token;
        
        public SendNewCambioContraseñaRequestBody() {
        }
        
        public SendNewCambioContraseñaRequestBody(string rut, string email, string token) {
            this.rut = rut;
            this.email = email;
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendNewCambioContraseñaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendNewCambioContraseñaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponseBody Body;
        
        public SendNewCambioContraseñaResponse() {
        }
        
        public SendNewCambioContraseñaResponse(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendNewCambioContraseñaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendNewCambioContraseñaResult;
        
        public SendNewCambioContraseñaResponseBody() {
        }
        
        public SendNewCambioContraseñaResponseBody(bool SendNewCambioContraseñaResult) {
            this.SendNewCambioContraseñaResult = SendNewCambioContraseñaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendActualizacionUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendActualizacionUsuario", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequestBody Body;
        
        public SendActualizacionUsuarioRequest() {
        }
        
        public SendActualizacionUsuarioRequest(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendActualizacionUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendActualizacionUsuarioRequestBody() {
        }
        
        public SendActualizacionUsuarioRequestBody(string rut, string email) {
            this.rut = rut;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendActualizacionUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendActualizacionUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponseBody Body;
        
        public SendActualizacionUsuarioResponse() {
        }
        
        public SendActualizacionUsuarioResponse(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendActualizacionUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendActualizacionUsuarioResult;
        
        public SendActualizacionUsuarioResponseBody() {
        }
        
        public SendActualizacionUsuarioResponseBody(bool SendActualizacionUsuarioResult) {
            this.SendActualizacionUsuarioResult = SendActualizacionUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPedidoDespachoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPedidoDespacho", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendPedidoDespachoRequestBody Body;
        
        public SendPedidoDespachoRequest() {
        }
        
        public SendPedidoDespachoRequest(WebServiceShop.ServiceCorreo.SendPedidoDespachoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPedidoDespachoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pedido_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendPedidoDespachoRequestBody() {
        }
        
        public SendPedidoDespachoRequestBody(int pedido_id, string email) {
            this.pedido_id = pedido_id;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPedidoDespachoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPedidoDespachoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendPedidoDespachoResponseBody Body;
        
        public SendPedidoDespachoResponse() {
        }
        
        public SendPedidoDespachoResponse(WebServiceShop.ServiceCorreo.SendPedidoDespachoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPedidoDespachoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendPedidoDespachoResult;
        
        public SendPedidoDespachoResponseBody() {
        }
        
        public SendPedidoDespachoResponseBody(bool SendPedidoDespachoResult) {
            this.SendPedidoDespachoResult = SendPedidoDespachoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEntregadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEntregado", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendEntregadoRequestBody Body;
        
        public SendEntregadoRequest() {
        }
        
        public SendEntregadoRequest(WebServiceShop.ServiceCorreo.SendEntregadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEntregadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pedido_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendEntregadoRequestBody() {
        }
        
        public SendEntregadoRequestBody(int pedido_id, string email) {
            this.pedido_id = pedido_id;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEntregadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEntregadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendEntregadoResponseBody Body;
        
        public SendEntregadoResponse() {
        }
        
        public SendEntregadoResponse(WebServiceShop.ServiceCorreo.SendEntregadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEntregadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEntregadoResult;
        
        public SendEntregadoResponseBody() {
        }
        
        public SendEntregadoResponseBody(bool SendEntregadoResult) {
            this.SendEntregadoResult = SendEntregadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEnvioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEnvio", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendEnvioRequestBody Body;
        
        public SendEnvioRequest() {
        }
        
        public SendEnvioRequest(WebServiceShop.ServiceCorreo.SendEnvioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEnvioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pedido_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendEnvioRequestBody() {
        }
        
        public SendEnvioRequestBody(int pedido_id, string email) {
            this.pedido_id = pedido_id;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendEnvioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendEnvioResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendEnvioResponseBody Body;
        
        public SendEnvioResponse() {
        }
        
        public SendEnvioResponse(WebServiceShop.ServiceCorreo.SendEnvioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendEnvioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendEnvioResult;
        
        public SendEnvioResponseBody() {
        }
        
        public SendEnvioResponseBody(bool SendEnvioResult) {
            this.SendEnvioResult = SendEnvioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCanceladoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCancelado", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendCanceladoRequestBody Body;
        
        public SendCanceladoRequest() {
        }
        
        public SendCanceladoRequest(WebServiceShop.ServiceCorreo.SendCanceladoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCanceladoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pedido_id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public SendCanceladoRequestBody() {
        }
        
        public SendCanceladoRequestBody(int pedido_id, string email) {
            this.pedido_id = pedido_id;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCanceladoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCanceladoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceCorreo.SendCanceladoResponseBody Body;
        
        public SendCanceladoResponse() {
        }
        
        public SendCanceladoResponse(WebServiceShop.ServiceCorreo.SendCanceladoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCanceladoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendCanceladoResult;
        
        public SendCanceladoResponseBody() {
        }
        
        public SendCanceladoResponseBody(bool SendCanceladoResult) {
            this.SendCanceladoResult = SendCanceladoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_CorreoSoapChannel : WebServiceShop.ServiceCorreo.WebService_CorreoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_CorreoSoapClient : System.ServiceModel.ClientBase<WebServiceShop.ServiceCorreo.WebService_CorreoSoap>, WebServiceShop.ServiceCorreo.WebService_CorreoSoap {
        
        public WebService_CorreoSoapClient() {
        }
        
        public WebService_CorreoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_CorreoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CorreoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_CorreoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendReservaResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendReserva(WebServiceShop.ServiceCorreo.SendReservaRequest request) {
            return base.Channel.SendReserva(request);
        }
        
        public bool SendReserva(string rut, int id_pedido, string email) {
            WebServiceShop.ServiceCorreo.SendReservaRequest inValue = new WebServiceShop.ServiceCorreo.SendReservaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendReservaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_pedido = id_pedido;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendReservaResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendReserva(inValue);
            return retVal.Body.SendReservaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendReservaResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendReservaAsync(WebServiceShop.ServiceCorreo.SendReservaRequest request) {
            return base.Channel.SendReservaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendReservaResponse> SendReservaAsync(string rut, int id_pedido, string email) {
            WebServiceShop.ServiceCorreo.SendReservaRequest inValue = new WebServiceShop.ServiceCorreo.SendReservaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendReservaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_pedido = id_pedido;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendReservaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendPagoResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendPago(WebServiceShop.ServiceCorreo.SendPagoRequest request) {
            return base.Channel.SendPago(request);
        }
        
        public bool SendPago(string rut, int id_pedido, string email) {
            WebServiceShop.ServiceCorreo.SendPagoRequest inValue = new WebServiceShop.ServiceCorreo.SendPagoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendPagoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_pedido = id_pedido;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendPagoResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendPago(inValue);
            return retVal.Body.SendPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPagoResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendPagoAsync(WebServiceShop.ServiceCorreo.SendPagoRequest request) {
            return base.Channel.SendPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPagoResponse> SendPagoAsync(string rut, int id_pedido, string email) {
            WebServiceShop.ServiceCorreo.SendPagoRequest inValue = new WebServiceShop.ServiceCorreo.SendPagoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendPagoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_pedido = id_pedido;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendUsuarioNuevo(WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest request) {
            return base.Channel.SendUsuarioNuevo(request);
        }
        
        public bool SendUsuarioNuevo(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest inValue = new WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendUsuarioNuevo(inValue);
            return retVal.Body.SendUsuarioNuevoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendUsuarioNuevoAsync(WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest request) {
            return base.Channel.SendUsuarioNuevoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendUsuarioNuevoResponse> SendUsuarioNuevoAsync(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest inValue = new WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendUsuarioNuevoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendUsuarioNuevoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendCambioContraseña(WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest request) {
            return base.Channel.SendCambioContraseña(request);
        }
        
        public bool SendCambioContraseña(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest inValue = new WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendCambioContraseñaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendCambioContraseña(inValue);
            return retVal.Body.SendCambioContraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendCambioContraseñaAsync(WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest request) {
            return base.Channel.SendCambioContraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCambioContraseñaResponse> SendCambioContraseñaAsync(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest inValue = new WebServiceShop.ServiceCorreo.SendCambioContraseñaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendCambioContraseñaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendCambioContraseñaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendNewCambioContraseña(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest request) {
            return base.Channel.SendNewCambioContraseña(request);
        }
        
        public bool SendNewCambioContraseña(string rut, string email, string token) {
            WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest inValue = new WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            inValue.Body.token = token;
            WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendNewCambioContraseña(inValue);
            return retVal.Body.SendNewCambioContraseñaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendNewCambioContraseñaAsync(WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest request) {
            return base.Channel.SendNewCambioContraseñaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendNewCambioContraseñaResponse> SendNewCambioContraseñaAsync(string rut, string email, string token) {
            WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest inValue = new WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendNewCambioContraseñaRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            inValue.Body.token = token;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendNewCambioContraseñaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendActualizacionUsuario(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest request) {
            return base.Channel.SendActualizacionUsuario(request);
        }
        
        public bool SendActualizacionUsuario(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest inValue = new WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendActualizacionUsuario(inValue);
            return retVal.Body.SendActualizacionUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendActualizacionUsuarioAsync(WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest request) {
            return base.Channel.SendActualizacionUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendActualizacionUsuarioResponse> SendActualizacionUsuarioAsync(string rut, string email) {
            WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest inValue = new WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendActualizacionUsuarioRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendActualizacionUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendPedidoDespacho(WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest request) {
            return base.Channel.SendPedidoDespacho(request);
        }
        
        public bool SendPedidoDespacho(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest inValue = new WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendPedidoDespachoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendPedidoDespacho(inValue);
            return retVal.Body.SendPedidoDespachoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendPedidoDespachoAsync(WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest request) {
            return base.Channel.SendPedidoDespachoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendPedidoDespachoResponse> SendPedidoDespachoAsync(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest inValue = new WebServiceShop.ServiceCorreo.SendPedidoDespachoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendPedidoDespachoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendPedidoDespachoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendEntregadoResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendEntregado(WebServiceShop.ServiceCorreo.SendEntregadoRequest request) {
            return base.Channel.SendEntregado(request);
        }
        
        public bool SendEntregado(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendEntregadoRequest inValue = new WebServiceShop.ServiceCorreo.SendEntregadoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendEntregadoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendEntregadoResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendEntregado(inValue);
            return retVal.Body.SendEntregadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEntregadoResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendEntregadoAsync(WebServiceShop.ServiceCorreo.SendEntregadoRequest request) {
            return base.Channel.SendEntregadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEntregadoResponse> SendEntregadoAsync(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendEntregadoRequest inValue = new WebServiceShop.ServiceCorreo.SendEntregadoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendEntregadoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendEntregadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendEnvioResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendEnvio(WebServiceShop.ServiceCorreo.SendEnvioRequest request) {
            return base.Channel.SendEnvio(request);
        }
        
        public bool SendEnvio(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendEnvioRequest inValue = new WebServiceShop.ServiceCorreo.SendEnvioRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendEnvioRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendEnvioResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendEnvio(inValue);
            return retVal.Body.SendEnvioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEnvioResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendEnvioAsync(WebServiceShop.ServiceCorreo.SendEnvioRequest request) {
            return base.Channel.SendEnvioAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendEnvioResponse> SendEnvioAsync(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendEnvioRequest inValue = new WebServiceShop.ServiceCorreo.SendEnvioRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendEnvioRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendEnvioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceCorreo.SendCanceladoResponse WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendCancelado(WebServiceShop.ServiceCorreo.SendCanceladoRequest request) {
            return base.Channel.SendCancelado(request);
        }
        
        public bool SendCancelado(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendCanceladoRequest inValue = new WebServiceShop.ServiceCorreo.SendCanceladoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendCanceladoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            WebServiceShop.ServiceCorreo.SendCanceladoResponse retVal = ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendCancelado(inValue);
            return retVal.Body.SendCanceladoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCanceladoResponse> WebServiceShop.ServiceCorreo.WebService_CorreoSoap.SendCanceladoAsync(WebServiceShop.ServiceCorreo.SendCanceladoRequest request) {
            return base.Channel.SendCanceladoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceCorreo.SendCanceladoResponse> SendCanceladoAsync(int pedido_id, string email) {
            WebServiceShop.ServiceCorreo.SendCanceladoRequest inValue = new WebServiceShop.ServiceCorreo.SendCanceladoRequest();
            inValue.Body = new WebServiceShop.ServiceCorreo.SendCanceladoRequestBody();
            inValue.Body.pedido_id = pedido_id;
            inValue.Body.email = email;
            return ((WebServiceShop.ServiceCorreo.WebService_CorreoSoap)(this)).SendCanceladoAsync(inValue);
        }
    }
}
