//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceShop.ServiceReference_PayTransbank {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference_PayTransbank.WebService_PayTransbankSoap")]
    public interface WebService_PayTransbankSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse HelloWorld(WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse> HelloWorldAsync(WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento buyOrder del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPago", ReplyAction="*")]
        WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse CrearPago(WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearPago", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse> CrearPagoAsync(WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento token del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoPago", ReplyAction="*")]
        WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse EstadoPago(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoPago", ReplyAction="*")]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse> EstadoPagoAsync(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPago", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequestBody Body;
        
        public CrearPagoRequest() {
        }
        
        public CrearPagoRequest(WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string buyOrder;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string urlReturn;
        
        public CrearPagoRequestBody() {
        }
        
        public CrearPagoRequestBody(string buyOrder, int amount, string urlReturn) {
            this.buyOrder = buyOrder;
            this.amount = amount;
            this.urlReturn = urlReturn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearPagoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponseBody Body;
        
        public CrearPagoResponse() {
        }
        
        public CrearPagoResponse(WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.Pago CrearPagoResult;
        
        public CrearPagoResponseBody() {
        }
        
        public CrearPagoResponseBody(WebServiceShop.ServiceReference_PayTransbank.Pago CrearPagoResult) {
            this.CrearPagoResult = CrearPagoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadoPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoPago", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequestBody Body;
        
        public EstadoPagoRequest() {
        }
        
        public EstadoPagoRequest(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoPagoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string token;
        
        public EstadoPagoRequestBody() {
        }
        
        public EstadoPagoRequestBody(string token) {
            this.token = token;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EstadoPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EstadoPagoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponseBody Body;
        
        public EstadoPagoResponse() {
        }
        
        public EstadoPagoResponse(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EstadoPagoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EstadoPagoResult;
        
        public EstadoPagoResponseBody() {
        }
        
        public EstadoPagoResponseBody(string EstadoPagoResult) {
            this.EstadoPagoResult = EstadoPagoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService_PayTransbankSoapChannel : WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService_PayTransbankSoapClient : System.ServiceModel.ClientBase<WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap>, WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap {
        
        public WebService_PayTransbankSoapClient() {
        }
        
        public WebService_PayTransbankSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService_PayTransbankSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_PayTransbankSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService_PayTransbankSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.HelloWorld(WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequestBody();
            WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse retVal = ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse> WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.HelloWorldAsync(WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.HelloWorldResponse> HelloWorldAsync() {
            WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.HelloWorldRequestBody();
            return ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.CrearPago(WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest request) {
            return base.Channel.CrearPago(request);
        }
        
        public WebServiceShop.ServiceReference_PayTransbank.Pago CrearPago(string buyOrder, int amount, string urlReturn) {
            WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequestBody();
            inValue.Body.buyOrder = buyOrder;
            inValue.Body.amount = amount;
            inValue.Body.urlReturn = urlReturn;
            WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse retVal = ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).CrearPago(inValue);
            return retVal.Body.CrearPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse> WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.CrearPagoAsync(WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest request) {
            return base.Channel.CrearPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.CrearPagoResponse> CrearPagoAsync(string buyOrder, int amount, string urlReturn) {
            WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.CrearPagoRequestBody();
            inValue.Body.buyOrder = buyOrder;
            inValue.Body.amount = amount;
            inValue.Body.urlReturn = urlReturn;
            return ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).CrearPagoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.EstadoPago(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest request) {
            return base.Channel.EstadoPago(request);
        }
        
        public string EstadoPago(string token) {
            WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequestBody();
            inValue.Body.token = token;
            WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse retVal = ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).EstadoPago(inValue);
            return retVal.Body.EstadoPagoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse> WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap.EstadoPagoAsync(WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest request) {
            return base.Channel.EstadoPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebServiceShop.ServiceReference_PayTransbank.EstadoPagoResponse> EstadoPagoAsync(string token) {
            WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest inValue = new WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequest();
            inValue.Body = new WebServiceShop.ServiceReference_PayTransbank.EstadoPagoRequestBody();
            inValue.Body.token = token;
            return ((WebServiceShop.ServiceReference_PayTransbank.WebService_PayTransbankSoap)(this)).EstadoPagoAsync(inValue);
        }
    }
}
